rabbitmq:
  image: rabbitmq:management
#  ports:
#    - 15672:15672
redis:
  image: redis
sensu:
  build: sensu
  volumes:
    - ./sensu-conf-d:/etc/sensu/conf.d
#  ports:
#    - 4567:4567
  links:
    - rabbitmq
    - redis
uchiwa:
  image: uchiwa/uchiwa
  volumes:
    - ./uchiwa-config:/config
  ports:
    - 3000:3000
  links:
    - sensu
    - rabbitmq
    - redis
# Sensu-client is just an example about how to setup a sensu-client
# Remove it if you know how sensu-client work
sensu-client:
  build: sensu-client
  links:
    - rabbitmq
    - redis