rabbitmq:
  image: rabbitmq:management
  # Rabbitmq need to be public so other sensu-client could send the data to
  ports:
    - 15672:15672
redis:
  image: redis
sensu:
  build: sensu
  volumes:
    # Path to your sensu conf.d
    - ../sample/sensu-conf-d:/etc/sensu/conf.d
  links:
    - rabbitmq
    - redis
uchiwa:
  image: uchiwa/uchiwa
  volumes:
    # Path to your uchiwa config folder. Feel free to customize it
    - ../sample/uchiwa-config:/config
  ports:
    - 3000:3000
  links:
    - sensu